### ISSUE TITLE
Draw the Use Case Diagram

### ISSUE THREAD

**Issue by joeltyy** [fwishyy/inf2001-p9-1#10]
Task title ID: #10

> **Task**: Draw the Use Case Diagram

> **Goals**: To understand and describe the high-level functions and scope of a system

> **Completion Criteria**: Use Case Diagram clearly describes the high-level functions of the system

> **Allocated Time**: 7 Days

> **Start Date**: 14 September 2023

> **End: Date**: 21 September 2023

> **Owner**: Joel

> **Status**: In-Progress

> **Priority**: HIGH

**Comment by joeltyy** [comment]
What has been completed:

1. Manager
    - Create Job Assignment
    - View Crew Members' Availability
    - Allocate Job Assignment to available Crew Members
    - Validate Job Assignment Rejection Request
    - Modify Job Assignment
    - View Job Assignments of all Crew Members
2. Crew Member
    - View Job Assignments
        - Confirm / Reject Job Assignment
    - Indicate Non-Availability
3. IT Admin
    - Manage Employee Accounts

TO DO:

**Comment by sweeduo3** [comment]
> **Describe the work done in detail**: Created the use case diagram based on the use case description. This is used in the aid of completing M1 Report.

> **How does the work affect**: It affects the overall project in ways of visualising the overall high level understanding of how the system would interact with each other. Without the Use Case Diagram, the client would not understand how the system would work.

> **Start Date**: 14 September 2023

> **End: Date**: 21 September 2023
