### ISSUE TITLE
4.4. Create and Calculate Project Estimation

### ISSUE THREAD

**Issue by joeltyy** [fwishyy/inf2001-p9-1#11]
Task title ID: #11

> **Task**: Estimating the effort required for the project using Function Points

> **Goals**: By using the Function Points calculation method on the Requirements, Use Case Diagram and Use Case Descriptions that the team has gathered and analysed, the goal of the task is to first calculate the Unadjusted Standard Function points and then account for the Technical Complexities

> **Completion Criteria**:  At the end of the task, we should have an estimation of the size of the project using function points, fully adjusted using the Technical Complexity Factor (TCF)

> **Allocated Time**: 1 week

> **Start Date**: 20 Sep 2023

> **End: Date**: 22 Sep 2023

> **Owner**: Nonsouris

> **Status**: In-Progress

> **Priority**: HIGH

**Comment by fwishyy** [comment]
> **Describe the work done in detail**: The estimated work required to complete the product was calculated using a mix of both Function Points and the Cost Constructive Model techniques, then adjusted using the team's decided Technical Complexity Factors. We have a resulting estimation on the duration, in hours, required to complete the project.

> **How does the work affect**: The work done allows both the team and the client to understand the resource required to complete the work, and estimate a timeline for the work to be completed.

> **Start Date**: 20 September 2023

> **End: Date**: 22 September 2023
