### ISSUE TITLE
Draft follow up email

### ISSUE THREAD

**Issue by joeltyy** [fwishyy/inf2001-p9-1#12]
Task title ID: #12

> **Task**: Draft and send a follow-up email with the client

> **Goals**: To gather requirements about the project and clarify any ambiguity.

> **Completion Criteria**: 

> **Allocated Time**: 1 Day

> **Start Date**: 14 September 2023

> **End: Date**: 15 September 2023

> **Owner**: Bryan

> **Status**: In-Progress

> **Priority**: HIGH

**Comment by sweeduo3** [comment]
> **Describe the work done in detail**: Follow-up email have been sent to the client. The Follow-up email consist of the requirements that was discussed during the face-to-face meeting and further clarifications on the requirements.
> **How does the work affect**: It is to prevent any ambiguity and ensure that the team is on the same page with the client requirements.

> **Start Date**: 14 September 2023

> **End: Date**: 15 September 2023
