### ISSUE TITLE
6.2. Finalize M2 Report

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#17]
Task title ID: #17

> **Task**: To complete the M2 Report

> **Goals**: Ensure the report is checked and completed so as to submit the report via xSite

> **Completion Criteria**: Ensure that Component diagram (#19), Class Diagram (#20), Sequence Diagram (#21) is being done and finalized. 

> **Allocated Time**:

> **Start Date**: 17 Oct 23

> **End: Date**: 28 Oct 23

> **Owner**: Keith

> **Status**: In progress

> **Priority**: HIGH

**Comment by fwishyy** [comment]
Describe the work done in detail: The M2 report has been checked through to ensure that the required sections have been completed, up-to-standard across the report and prepared for submission

How does the work affect completion deadline: This ensures that one member is responsible for ensuring that the report is consistent, and meets the standards agreed upon by the team.

Start Date: 22 Oct 2023

End: Date: 23 Oct 2023
