### ISSUE TITLE
6.1. Draw Component diagram

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#19]
Task title ID: #19

> **Task**:  To illustrate the component diagram of the product design.

> **Goals**: To illustrate how the overall design of certain parts of the project comes together as one.

> **Completion Criteria**:  Ensure the component diagram comes together as one and showing it clearly.

> **Allocated Time**: 3 Days

> **Start Date**: 24 Oct 23

> **End: Date**: 27 Oct 23

> **Owner**: Davis

> **Status**: No Started

> **Priority**: HIGH

**Comment by fwishyy** [comment]
Describe the work done in detail: The component diagrams have been fully constructed from the class diagrams to represent the different entities from the system at a higher level

How does the work affect completion deadline: The component diagram illustrates the relationship between different components of the system, providing a high level view of how they interact with one another

Start Date: 22 Oct 2023

End: Date: 23 Oct 2023
