### ISSUE TITLE
Background research on coach industry (by 9/9/23)

### ISSUE THREAD

**Issue by Nonsouris** [fwishyy/inf2001-p9-1#2]
can also take reference from other industries that have problems managing manpower, navy crews, cruise, aircrafts, etc as well as  (pain points, similar software, etc)

**Comment by fwishyy** [comment]
This task was completed prior to the first client consultation. I combed through some of the old research papers outlining the problems regarding Workload Scheduling management in both transport and similar industries to better understand the pain points the client would potentially face on the matter.
