### ISSUE TITLE
5.4. Draw Sequence diagram 1

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#21]
Task title ID: #21

> **Task**: To illustrate one of the use case to the sequence diagram.

> **Goals**:  To draw out the first sequence diagram

> **Completion Criteria**: 

> **Allocated Time**: 5 Days

> **Start Date**: 19 Oct 23

> **End: Date**: 23 Oct 23

> **Owner**: Joel

> **Status**: Completed

> **Priority**: HIGH

**Comment by joeltyy** [comment]
Describe the work done in detail: The first sequence diagram was drawn, and it was drawn according to the use case of allocating job assignments to Crew Members by the Manager

How does the work affect completion deadline: It helps to visualize the flow of events for the use case of allocating job assignments to Crew Members by the Manager, hence improving the design of the product and collaboration amongst developers in the design and testing phase

Start Date: 19 Oct 2023

End: Date: 23 Oct 2023
