### ISSUE TITLE
Formulate questions for client

### ISSUE THREAD

**Issue by Nonsouris** [fwishyy/inf2001-p9-1#3]
To ask during consultation:
- Domain
- Organisation
- Auxiliary questions
- Requirement Clarification

**Comment by sweeduo3** [comment]
Formulating of questions for client has been completed and we had our meeting with the client on 7 September 2023

**Comment by sweeduo3** [comment]
Formulating of questions for client has been completed and we had our meeting with the client on 7 September 2023
