### ISSUE TITLE
4.6. Update Use Case Diagram

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#32]
Task title ID: #32

> **Task**:  To update the use case diagram based on the marker's feedback.

> **Goals**: Update the case diagram as:
> - External database should be shown.
> - Use of «extend» relationship seems inappropriate.
> - Use case diagram and use case description do not match

> **Completion Criteria**:  Ensure the use case diagram is matched exactly with the use case description and show the external database. 

> **Allocated Time**: 7 Days

> **Start Date**: 12 Oct 2023

> **End: Date**: 18 Oct 2023

> **Owner**: Bryan

> **Status**: Completed

> **Priority**: HIGH

**Comment by sweeduo3** [comment]
What has been completed:

- Removed the unnecessary Use Cases
- Added a Database as another actor

**Comment by sweeduo3** [comment]
Describe the work done in detail: Updated the Use Case Diagram according to the updated Use Case Description.

How does the work affect:  Use Case Diagrams are a powerful tool in software engineering that play a critical role in understanding, documenting, and communicating the functional requirements of a software system. They have a far-reaching impact on the entire software development process, from requirement gathering and design to testing, project management, and ultimately the success of the project by ensuring that the delivered software meets user expectations and requirements.

Start Date: 12 Oct 2023

End: Date: 18 Oct 2023
