### ISSUE TITLE
4.5. Update Use Case Description

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#33]
Task title ID: #33

> **Task**:  To update the use case description based on the marker's feedback.

> **Goals**: Update the use case descriptions to be more informative as well as how validation, verification and decision took place.

> **Completion Criteria**:  Ensure all use case description are informative and still maintained part of the updated function and non-functional requirements.

> **Allocated Time**: 7 Days

> **Start Date**: 12 Oct 2023

> **End: Date**: 18 Oct 2023

> **Owner**: Bryan

> **Status**: Completed

> **Priority**: HIGH

**Comment by sweeduo3** [comment]
What has been completed:

- Removed the Use Case Descriptions that is not required
- Updated the Use Case Names to match with Use Case Diagram

**Comment by sweeduo3** [comment]
Describe the work done in detail: Updated the Use Case Description, modifying UC-2 to UC-13 and removing UC-1 and UC-9. Added UC-15 to UC-18

How does the work affect: Use case descriptions are a critical tool in software engineering that affect various aspects of the software development lifecycle. They provide a detailed and user-centric perspective on the software's functionality, serving as a blueprint for the development, testing, and maintenance of the system while fostering effective communication and alignment with stakeholders' needs and expectations.

Start Date: 12 Oct 2023

End: Date: 18 Oct 2023
