### ISSUE TITLE
4.3. Update Functional Requirements

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#34]
Task title ID: #34

> **Task**:  To update the functional requirement based on the marker's feedback.

> **Goals**: Update the functional requirement based on the 7 good traits based on the system perspective.

> **Completion Criteria**:  Ensure all functional requirements are updated and based on the system perspective.

> **Allocated Time**: 7 Days

> **Start Date**: 05 Oct 2023

> **End: Date**: 11 Oct 2023

> **Owner**: Keith

> **Status**: Completed

> **Priority**: HIGH

**Comment by fwishyy** [comment]
Describe the work done in detail: The functional requirements have been updated to reflect the feedback received during M1.

How does the work affect completion deadline: This ensures that the functional requirements are properly updated, to standard, and ensures that the development going forward aligns with these improved requirements.

Start Date: 05 Oct 2023

End: Date: 11 Oct 2023
