### ISSUE TITLE
4.1. Reorganize and update Gantt Chart

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#35]
Task title ID: #35

> **Task**:  To update the gantt chart based on the feedback from the marker.

> **Goals**: Update the tasks to break down into smaller sections..

> **Completion Criteria**:  Ensure all tasks are split further and update changes to the M2 section on the specific tasks needed to be done and put into M2 report.

> **Allocated Time**: 10 Days

> **Start Date**: 25 Sep 23

> **End: Date**: 04 Oct 23

> **Owner**: Evander

> **Status**: Completed

> **Priority**: HIGH

**Comment by evanderleng** [comment]
Describe the work done in detail: Updated the Gantt chart to have SDLC workflow

How does the work affect: Gantt chart affects the group's progress on the project, and acts as a timetable to make sure the project is delivered on schedule

Start Date: 25 Sep 2023

End: Date: 04 Oct 2023
