### ISSUE TITLE
4.4. Update Non-Functional Requirement

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#36]
Task title ID: #36

> **Task**:  To update the non-functional requirement based on the marker's feedback.

> **Goals**: Update the non-functional requirement based on the 7 good traits based on the system perspective.

> **Completion Criteria**:  Ensure all non-functional requirements are updated and based on the system perspective.

> **Allocated Time**: 7 Days

> **Start Date**: 05 Oct 2023

> **End: Date**: 11 Oct 2023

> **Owner**: Bryan

> **Status**: Completed

> **Priority**: HIGH

**Comment by sweeduo3** [comment]
Describe the work done in detail: Updated the Non-Functional Requirements to fit the system perspective, 

How does the work affect: Non-functional requirements have a significant impact on software projects as they directly affect the software's performance, reliability, security, user experience, and overall success. Neglecting these requirements can lead to system failures, user dissatisfaction, increased maintenance costs, and legal issues. 

Start Date: 05 Oct 2023

End: Date: 11 Oct 2023
