### ISSUE TITLE
5.5. Draw Sequence Diagram 2

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#39]
Task title ID: #39

> **Task**: To illustrate one of the use case to the sequence diagram.

> **Goals**:  To draw out the second sequence diagram

> **Completion Criteria**: 

> **Allocated Time**: 5 Days

> **Start Date**: 19 Oct 23

> **End: Date**: 23 Oct 23

> **Owner**: Bryan

> **Status**: Completed

> **Priority**: HIGH

**Comment by joeltyy** [comment]
Describe the work done in detail: The second sequence diagram was drawn, and it was drawn according to the use case of accepting / rejecting job assignments assigned to a Crew Member

How does the work affect completion deadline: It helps to visualize the flow of events for the use case of accepting / rejecting job assignments assigned to a Crew Member, hence improving the design of the product and collaboration amongst developers in the design and testing phase

Start Date: 19 Oct 2023

End: Date: 23 Oct 2023
