### ISSUE TITLE
5.2. Document Class Diagram

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#42]
Task title ID: #42

> **Task**:  To document the class diagram

> **Goals**: Verify the methods and variables used in the class diagram

> **Completion Criteria**:  Ensure all methods and variables in the class diagram are verified

> **Allocated Time**: 2 Days

> **Start Date**: 19 Oct 23

> **End: Date**: 20 Oct 23

> **Owner**: Evander

> **Status**: Not started

> **Priority**: HIGH

**Comment by evanderleng** [comment]
Describe the work done in detail: The class diagram has been documented, with explanations on the design and a list of all objects within the class diagram included

How does the work affect: The Documentation for Class diagram would help team members to better understand the structure of the project, allowing for improved cooperation throughout the rest of the project

Start Date: 25 Sep 2023

End: Date: 04 Oct 2023
