### ISSUE TITLE
5.6. Document Sequence Diagram

### ISSUE THREAD

**Issue by chinhan98** [fwishyy/inf2001-p9-1#47]
Task title ID: #42

> **Task**:  To document the Sequence Diagrams

> **Goals**: To explain the Sequence Diagrams flow based on the 2 Use Case picked.

> **Completion Criteria**:  Ensure the diagrams are explained with the flow.

> **Allocated Time**: 2 Days

> **Start Date**: 22 Oct 23

> **End: Date**: 23 Oct 23

> **Owner**: Joel

> **Status**: In Progress

> **Priority**: HIGH

**Comment by joeltyy** [comment]
Describe the work done in detail: The sequence diagrams have been fully documented and explained, with a summary of how the flow of events looks like for each of the chosen use cases.

How does the work affect completion deadline: This helps to better explain the flow of events for each of the chosen use cases in simple terms and allows for a better understanding of how the product should function, hence allowing for improved collaboration and coordination amongst developers in the testing and development phase

Start Date: 22 Oct 2023

End: Date: 23 Oct 2023
