### ISSUE TITLE
3.5. M1 Report

### ISSUE THREAD

**Issue by Nonsouris** [fwishyy/inf2001-p9-1#5]
Task title ID: #05

> **Task**:  Document the project specification on M1.

> **Goals**: To ensure all of the requirements are being documented and submit before the deadline on xSite.

> **Completion Criteria**:  Ensure Use Case Diagram (#10), Use Case Descriptions (#7), Project Planning (#11), Activity Diagrams (#25), Requirements Specification (#8, #9) are completed.

> **Allocated Time**: 13 Days

> **Start Date**: 11 Sep 23

> **End: Date**: 23 Sep 23

> **Owner**: @fwishyy 

> **Status**: In-Progress

> **Priority**: HIGH

**Comment by fwishyy** [comment]
> **Describe the work done in detail**: The sections necessary for the M1 report template have been filled up by the different members in charge. The team has also gathered to deconflict, iron out and tidy the report content, and the M1 report has been submitted to the assessors.

> **How does the work affect**: Milestone 1 ensures that the team correctly represents the requirements of the client before proceeding with the advancing phases of the SDLC

> **Start Date**: 11 September 2023

> **End: Date**: 23 September 2023
