### ISSUE TITLE
Come up with Use Case Description

### ISSUE THREAD

**Issue by joeltyy** [fwishyy/inf2001-p9-1#7]
Task title ID: #07

> **Task**: To describe all the use case descriptions.

> **Goals**: List the use case and describe all the possible scenario.

> **Completion Criteria**: Ensure every use case is being mentioned based on the Function Requirements.

> **Allocated Time**: 5 Days

> **Start Date**: 15 Sep 23

> **End: Date**:

> **Owner**: Chin Han

> **Status**: 

> **Priority**: HIGH

**Comment by chinhan98** [comment]
What's been done:

- General use case for staff/employee
- Not done:

Manager use case
- IT Admin use case
- Others Functional Requirement needed

**Comment by joeltyy** [comment]
Describe the work done in detail: Use Case Descriptions have been drafted based on functional requirements, and further grouped by user roles. Use case descriptions have also been added into the M1 report

How does the work affect: Provides a better understanding for Use Case Diagrams and Activity Diagram

Start Date: 15 September 2023

End: Date: 21 September 2023
