### ISSUE TITLE
3.2. Formulate Non-Functional Requirements

### ISSUE THREAD

**Issue by joeltyy** [fwishyy/inf2001-p9-1#9]
Task title ID: #09

> **Task**: List out all of the Non-Functional Requirements

> **Goals**: Find all the required Non-Functional Requirements based on the objective of the client's product requirements.

> **Completion Criteria**:  Ensure all of the non-functional requirement is being specified.

> **Allocated Time**: 3 Days

> **Start Date**: 16 Sep 2023

> **End: Date**: 18 Sep 2023

> **Owner**: @Nonsouris 

> **Status**: Completed

> **Priority**: HIGH

**Comment by fwishyy** [comment]
> **Describe the work done in detail**: The non-functional requirements have been created and sorted into Performance, Safety, and miscellaneous categories.

> **How does the work affect**: The work done ensures that the client and team are clear of the performance requirements asked of the product, and that it complies with the safety laws agreed upon in the project brief, and later on in the client meetings, therefore fulfilling the task.

> **Start Date**: 16 September 2023

> **End: Date**: 18 September 2023
